FROM node:20-alpine AS builder
WORKDIR /app
RUN corepack enable
COPY package.json pnpm-workspace.yaml tsconfig.base.json ./
COPY packages ./packages
COPY apps/vault-web ./apps/vault-web
RUN npm install -g pnpm && pnpm install --frozen-lockfile || pnpm install
RUN pnpm --filter @omnisecure/core --filter @omnisecure/crypto --filter @omnisecure/vault-web run build

FROM nginx:alpine
COPY docker/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/apps/vault-web/dist /usr/share/nginx/html
EXPOSE 80
